name: Generate resume pdf

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: contributions-github-actions
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: bash -x build.sh
      - uses: amondnet/vercel-action@v20
        with:
          working-directory: ./static
          vercel-args: "--prod"
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}} # Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} # Required
      - uses: amondnet/vercel-action@v20
        with:
          working-directory: ./resume-redirect
          vercel-args: "--prod"
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.REDIRECT_ORG_ID}} # Required
          vercel-project-id: ${{ secrets.REDIRECT_PROJECT_ID}} # Required
